//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesID
    {
        public int RoleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AdminID { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
    }
}
