//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_REPORT1
    {
        public int PROJECTID { get; set; }
        public string PROJECTNAME { get; set; }
        public string STEPNAME { get; set; }
        public Nullable<System.DateTime> COMMENTCREATIONDATE { get; set; }
        public string COMMENT_OWNER { get; set; }
        public string COMMENTS { get; set; }
        public string FILENAME { get; set; }
        public string PREVIOUSSTATUS { get; set; }
        public string CURRENTSTATUS { get; set; }
        public string REASON { get; set; }
        public Nullable<System.DateTime> STATUSCHANGEDATE { get; set; }
        public string STATUS_OWNER { get; set; }
    }
}
