//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StepDetail()
        {
            this.Comments = new HashSet<Comment>();
            this.Justifications = new HashSet<Justification>();
        }
    
        public int StepID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> EstStartDate { get; set; }
        public Nullable<System.DateTime> EstEndDate { get; set; }
        public Nullable<System.DateTime> ActStartDate { get; set; }
        public Nullable<System.DateTime> ActEndDate { get; set; }
        public string StepName { get; set; }
        public Nullable<int> MasterID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Justification> Justifications { get; set; }
        public virtual MasterStep MasterStep { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
